<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
		public function getTaskNoFinish($idUsuario)	{

			try {
	            $em  = $this->getEntityManager();
	            $stmt = $em->getConnection()->prepare("SELECT * FROM `todo` WHERE estado <> 'FINALIZADA' AND user_id = :idUsuario");
	            $stmt->bindParam(':idUsuario',$idUsuario);
	            $stmt->execute();
			    $res = $stmt->fetchAll();
			    return $res;
		    } catch (\Doctrine\ORM\NoResultException $exception) {
		        return null;
		    }
		//	return $res;
		}	
}
