#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

list_tasks:
    path: /todo/{_locale}/list/tasks
    defaults: { _controller: AppBundle:Todo:listTask,_locale: es }
    requirements:
        _locale: 'en|es'
#        m: \d+

create_task:
    path: /todo/{_locale}/create/task
    defaults: { _controller: AppBundle:Todo:createTask,_locale: es }
    requirements:
        _locale: 'en|es'

remove_task:
    path: /todo/{_locale}/remove/task/{idTask}
    defaults: { _controller: AppBundle:Todo:removeTask,_locale: es }
    requirements:
        _locale: 'en|es'
        idTask: \d+    

edit_task:
    path: /todo/{_locale}/edit/task/{idTask}
    defaults: { _controller: AppBundle:Todo:editTask,_locale: es }
    requirements:
        _locale: 'en|es'
        idTask: \d+          

setStateAjax:
    path:   /todo/setState/{idTask}
    defaults: { _controller: AppBundle:Todo:setStateAjax, _locale: es }
    requirements:
        _locale: 'en|es' 
        idTask: \d+       

########    LOGIN/LOGOUT  ##########

login:
    path: /
    defaults: { _controller: AppBundle:Security:loginAdmin }

login_check:
    path: /login_check

logout:
    path: /logout        


formulario_registro:
    path:   /registro
    defaults: {_controller: AppBundle:User:registro }
    methods:  [POST]    

########    USUARIO  ##########

create_user:
    path:  /todo/admin/{_locale}/create/user
    defaults: { _controller: AppBundle:User:createUser, _locale: es }
    requirements:
        _locale: 'en|es'

show_users:
    path: /todo/admin/{_locale}/show/users
    defaults: { _controller: AppBundle:User:showUsers,_locale: es }
    requirements:
        _locale: 'en|es'

edit_user:
    path: /todo/admin/{_locale}/edit/user/{idUser}
    defaults: { _controller: AppBundle:User:editUser,_locale: es }
    requirements:
        _locale: 'en|es'
        idUser: \d+  